# Generated by Django 5.2.8 on 2025-11-19 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('idPrestamo', models.AutoField(primary_key=True, serialize=False)),
                ('horaEntrega', models.TimeField()),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
