# Generated by Django 5.2.8 on 2025-11-19 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prestamos', '0001_initial'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='idReserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.reserva'),
        ),
    ]
