# Generated by Django 5.2.8 on 2025-12-01 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_alter_prestamo_idempleado'),
        ('usuarios', '0003_remove_perfilusuario_contrasena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='idEmpleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario'),
        ),
    ]
