# Generated by Django 5.2.8 on 2025-11-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadServicio',
            fields=[
                ('idUnidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombreUnidad', models.CharField(max_length=100)),
                ('horarioInicio', models.TimeField()),
                ('horarioFin', models.TimeField()),
                ('granularidad', models.CharField(max_length=20)),
            ],
        ),
    ]
