# Generated by Django 5.2.8 on 2025-11-19 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRecurso',
            fields=[
                ('idTipoRecurso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('idUnidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unidades.unidadservicio')),
            ],
        ),
    ]
