# Generated by Django 5.2.8 on 2025-12-01 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_nombrerol_rol_nombre_remove_rol_idrol_rol_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='contrasena',
        ),
    ]
