# Generated by Django 5.2.8 on 2025-12-02 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_perfilusuario_contrasena'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='celular',
            new_name='cellphonenumber',
        ),
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='identificacion',
            new_name='identification',
        ),
    ]
