# Generated by Django 5.2.8 on 2025-11-19 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('idRecurso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('foto', models.BinaryField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('D', 'Disponible'), ('O', 'Ocupado'), ('M', 'Mantenimiento')], default='D', max_length=1)),
                ('idTipoRecurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipos.tiporecurso')),
            ],
        ),
    ]
