# Generated by Django 5.2.8 on 2025-11-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='recursos/'),
        ),
    ]
