# Generated by Django 5.2.8 on 2025-11-19 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('idDisponibilidad', models.AutoField(primary_key=True, serialize=False)),
                ('diaSemana', models.CharField(choices=[('LU', 'Lunes'), ('MA', 'Martes'), ('MI', 'Miércoles'), ('JU', 'Jueves'), ('VI', 'Viernes'), ('SA', 'Sábado'), ('DO', 'Domingo')], max_length=2)),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
                ('idTipoRecurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipos.tiporecurso')),
            ],
        ),
    ]
